### ISSUE TITLE
Why can not use 'at' with minutes? 

### ISSUE THREAD

**Issue by 631068264** [dbader/schedule#130]
I want to start my program at the top of the hour like 23:00 or 5:00 interval  15 min

example :  23:00 23:25 23:30 ......
So how to do that ?

```
import time

import schedule


def a():
    print "fsdfdfd"


schedule.every(15).minutes.at("22:00").do(a)

while True:
    schedule.run_pending()
    time.sleep(1)
```

Error
```
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/ma/test.py", line 19, in <module>
    schedule.every(15).minutes.at("22:43").do(a)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/schedule/__init__.py", line 329, in at
    assert self.unit in ('days', 'hours') or self.start_day
AssertionError
```

So only hours and days can use **at** ? How to achieve my goal

**Comment by zeroarst** [comment]
Same question here, i want the task to be run at 30 every house. how can I do that?

**Comment by SijmenHuizenga** [comment]
Now you can! :tada:
