### ISSUE TITLE
ModuleNotFoundError: No module named 'schedule'

### ISSUE THREAD

**Issue by daniellygj** [dbader/schedule#264]
I already ran the command pip install schedule, I also tried pip3 install schedule. was installed correctly, but the error persists.

Traceback (most recent call last):
File "C:/Users/danny/PycharmProjects/Testes/file.py", line 1, in 
import schedule
ModuleNotFoundError: No module named 'schedule'

python 3.7, Windows10

**Comment by vonhng** [comment]
retrieve the package:`pip3 list | grep schedule`,and python2 existed  at this env？

**Comment by horacekm** [comment]
I also ran into this problem with schedule with unit tests. 
Environment:
```
OS: Fedora 29
Python: 3.7.2
pipenv: 2018.11.26
pip3: 18.1
schedule: 0.5.0 (same error in 0.4.3)
```

Steps to reproduce:

```
$ mkdir test-schedule
$ cd test-schedule
$ pipenv install schedule
$ pipenv shell
$ nosetests test_schedule_import.py
```
Content of `test_schedule_import.py`:
```
# -*- coding: utf-8 -*-

import schedule
from unittest import TestCase


class TestScheduleImport(TestCase):
    def test_nothing(self):
        self.assertTrue(True)
```

This works fine:
`$ python3 -m unittest test_schedule_import.py`

This doesn't:
`$ nosetests`
`$ green`

Running the file as is also works:
`$ python3 test_schedule_import.py`

In case of nosetests, the exception produced is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/horacek/tmp/test-schedule/test_schedule_import.py", line 3, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'
```

In case of [green](https://github.com/CleanCut/green):
```
Traceback (most recent call last):
  File "/usr/local/bin/green", line 11, in <module>
    load_entry_point('green==2.13.0', 'console_scripts', 'green')()
  File "/usr/local/lib/python3.7/site-packages/green/cmdline.py", line 69, in main
    result = run(test_suite, stream, args, testing)
  File "/usr/local/lib/python3.7/site-packages/green/runner.py", line 88, in run
    for target in toParallelTargets(suite, args.targets)]
  File "/usr/local/lib/python3.7/site-packages/green/loader.py", line 342, in toParallelTargets
    proto_test_list = toProtoTestList(suite)
  File "/usr/local/lib/python3.7/site-packages/green/loader.py", line 326, in toProtoTestList
    toProtoTestList(i, test_list, doing_completions)
  File "/usr/local/lib/python3.7/site-packages/green/loader.py", line 318, in toProtoTestList
    getattr(suite, exception_method)()
  File "/usr/local/lib/python3.7/site-packages/green/loader.py", line 82, in testFailure
    raise ImportError(message)
ImportError: Failed to import test_schedule_import computed from filename /home/horacek/tmp/test-schedule/test_schedule_import.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/green/loader.py", line 54, in loadFromModuleFilename
    __import__(dotted_module)
  File "/home/horacek/tmp/test-schedule/test_schedule_import.py", line 3, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'
```
The only difference I can think of between `schedule` and other modules I use is that `schedule` is all in one `__init__.py`, whereas other modules import files like `from ... import ...`.

**Comment by horacekm** [comment]
Found the issue for my problem: both `nosetests` and `green` were running from system-wide `/usr/bin`, not the actual virtualenv. Original question from @daniellygj might be also related to path settings, see this [SO question](https://stackoverflow.com/questions/19885821/how-do-i-import-modules-in-pycharm).
