### ISSUE TITLE
Installation fails on python 3.4.0

### ISSUE THREAD

**Issue by waghanza** [dbader/schedule#27]
Hi,

I am using ```schedule``` as a **cron**-like library. Installation on my ```OS X``` (```python3``` installed via ```brew```) has just being install, but I can't install on my production server (```debian```).

I've check my setups, I have ```3.4.0``` on my ```debian``` and ```3.4.1``` on my ```OS X```.

On ```python``` ```3.4.0```I have 
~~~python
Downloading/unpacking schedule
  Downloading schedule-0.3.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/schedule/setup.py) egg_info for package schedule
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip_build_root/schedule/setup.py", line 20, in <module>
        open('README.rst').read() + '\n\n' +
      File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1964: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 20, in <module>

  File "/tmp/pip_build_root/schedule/setup.py", line 20, in <module>

    open('README.rst').read() + '\n\n' +

  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1964: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip_build_root/schedule
Storing debug log for failure in /root/.pip/pip.log
~~~

Regards,

**Comment by dbader** [comment]
Closing because it's been fixed for a while.
