### ISSUE TITLE
Invalid time format error with 0.6.0

### ISSUE THREAD

**Issue by msoultan** [dbader/schedule#278]
I just received the following error:

```
Traceback (most recent call last):
  File "autofy.py", line 3716, in <module>
    schedule.every().tuesday.at('8:00').do(EmailFlipFlopReport)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 381, in at
    raise ScheduleValueError('Invalid time format')
schedule.ScheduleValueError: Invalid time format
```

I noticed the host was running 0.6.0 - when I forced the version to 0.5.0, the issue went away.  I'm guessing something changed here?

Thanks!
Mike

**Comment by ConnorSkees** [comment]
The issue here is that `at()` is being passed `'8:00'` instead of `'08:00'`. The hour needs a leading 0. The regular expression hasn’t changed from 0.5.0, but the check for it has: b530b30692fb78a0a51b99b0b4859c20f94c01c9
```
if self.unit == 'days' or self.start_day:
        if not re.match(r'^([0-2]\d:)?[0-5]\d:[0-5]\d$', time_str):
            raise ScheduleValueError('Invalid time format')
```
