### ISSUE TITLE
crash script after some inserts

### ISSUE THREAD

**Issue by gabrielhribeiro** [dbader/schedule#350]
Hi guys, i have an issue, the script runs correctly, but in some momment i have a crash output like the example:

--------------------------------example----------------------------------------------
insert
insert
insert
insert
insert
insert
Traceback (most recent call last):
  File "C:/Códigos/transfer_dash/transfer_dash_consulting.py", line 35, in <module>
    schedule.every(10).seconds.do(insert_mysql_query_1_instance)
  File "C:\Users\Gabriel H R David\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\schedule\__init__.py", line 440, in do
    self.job_func = functools.partial(job_func, *args, **kwargs)
TypeError: the first argument must be callable

Process finished with exit code 1

-----------------------------------exit-----------------------------------

---------------------------------my loop code--------------------------

if __name__ == '__main__':
       class_value = select_insert()    #class instance
        insert_mysql_query_1_instance = class_value.insert_mysql_query_1()  #function
        schedule.every(10).seconds.do(insert_mysql_query_1_instance)  #jbo schedule

   while True:
         schedule.run_pending()
        time.sleep(1)

-------------------------------exit------------------------------------------------------

What do you think about this error?

Thanks;

**Comment by gabrielhribeiro** [comment]
if __name__ == '__main__':
    while True:
        try:
            class_value = select_insert()
            insert_mysql_query_1_instance = class_value.insert_mysql_query_1()
            schedule.every(1).minutes.do(insert_mysql_query_1_instance)

            schedule.run_pending()
            time.sleep(60)
        except:
            pass
        else:
            break
        time.sleep(5)
