### ISSUE TITLE
AttributeError: 'InstallRequirement' object has no attribute 'markers'

### ISSUE THREAD

**Issue by Quenos** [dbader/schedule#372]
I'm trying pip install schedule but get the following errors. Also tried with sudo.
No other package named schedule is installed

`ERROR: Exception:
Traceback (most recent call last):
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 302, in run
    check_supported_wheels=not options.target_dir,
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 326, in get_requirements
    requirement_set.add_requirement(req_to_add)
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/req/req_set.py", line 92, in add_requirement
    if not install_req.match_markers(extras_requested):
  File "/Users/coenkuijpers/PycharmProjects/SpreadMonitor/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 286, in match_markers
    if self.markers is not None:
AttributeError: 'InstallRequirement' object has no attribute 'markers'`

**Comment by Quenos** [comment]
Appeared to be an issue with the environment.
Solved
